// React dependecies
import { Inter } from 'next/font/google'
// React Components
import Navigation from '@/components/navigation'
import Footer from '@/components/footer'
// Styling
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ryan Hemlock',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Test comment */}
      {/* Navigation */}
      <Navigation />

      {/* Body */}
      <body className={inter.className}>{children}</body>

      {/* Footer */}
      <Footer />

    </html>
  )
}
